[package]
name = "gd32vf103xx-hal"
version = "0.0.3"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
repository = "https://github.com/riscv-rust/gd32vf103xx-hal"
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for GD32VF103 microcontrollers"
keywords = ["riscv", "gd32", "hal"]
license = "ISC"
edition = "2018"

[dependencies]
gd32vf103-pac = "0.1"
riscv = "0.5.4"
riscv-rt = { version = "0.6.1", optional = true }
nb = "0.1.2"
void = { version = "1.0.2", default-features = false }

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]

[features]
rt = ["riscv-rt"]
