[package]
name = "gd32vf103xx-hal"
version = "0.1.0"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
repository = "https://github.com/riscv-rust/gd32vf103xx-hal"
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for gd32vf103 variants from the official RISC-V Rust Team" 
keywords = ["riscv", "gd32", "hal"]
license = "ISC"
edition = "2018"

[dependencies]
embedded-hal = "0.2"
gd32vf103-pac = "0.1"
riscv = "0.5.4"
riscv-rt = { version = "0.6.1", optional = true }

[features]
rt = ["riscv-rt"]
