[package]
name = "gd32vf103xx-hal"
version = "0.1.0"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
repository = "https://github.com/riscv-rust/gd32vf103xx-hal"
categories = ["embedded", "hardware-support", "no-std"]
description = "HAL for GD32VF103 microcontrollers"
keywords = ["riscv", "gd32", "hal"]
license = "ISC"
edition = "2018"

[dependencies]
gd32vf103-pac = "0.1"
riscv = "0.5.4"
riscv-rt = { version = "0.6.1", optional = true }

[dependencies.void]
default-features = false
version = "1.0.2"

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]

[dev-dependencies]
panic-halt = "0.2"

[features]
rt = ["riscv-rt"]

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true
